name: CI for Development

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for better SonarCloud analysis

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Run tests with coverage
        run: |
          dotnet test Wildlife_Tests/Wildlife_Tests.csproj \
            --configuration Release \
            --no-build \
            --collect:"XPlat Code Coverage" \
            --results-directory TestResults/ \
            --logger trx \
            --logger "html;logfilename=testResults.html" \
            -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover

      - name: List coverage files (debug)
        run: |
          echo "Generated coverage files:"
          find TestResults -name "*.xml" -type f
          ls -la TestResults/

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=${ Matta5_Wildlife-BackEnd}
            -Dsonar.organization=${ mathijs-van-den-heilignberg }
            -Dsonar.sources=.
            -Dsonar.exclusions=**/bin/**,**/obj/**,**/*.Tests/**,TestResults/**
            -Dsonar.cs.opencover.reportsPaths=TestResults/**/coverage.opencover.xml